function getDeck() {
  return { black: black(), white: white() };
}

function black() {
  return [
    "Christmas would be incomplete without __________.",
    "King Tut brought __________ to the people of Arizona.",
    "Madonna is now embracing the curative powers of __________.",
    "Michael would've gotten away with it, if it hadn't been for __________.",
    "Gilligan discovered a primitive tribe that worships __________.",
    "Baseball fanatics came here to __________.",
    "I could tell you about __________, but then I'd have to kill you.",
    "You are invited to the theatre tonight to watch __________: The Musical.",
    "I'm having a problem with __________ and don't want your advice.",
    "Due to a major lawsuit, McDonalds no longer offers __________.",
    "During geometry class, I like to think about __________.",
    "She who controls __________ controls the world.",
    "I found out too late that you can't cheer up Godzilla with __________.",
    "Too bad I lost the instruction manual for __________.",
    "I'm sorry, Dr. Lisa, but I couldn't complete my homework because of __________.",
    "In Michael's final moments, __________ went through his mind.",
    "They say that the White House has a secret room devoted to __________.",
    "Sea World has opened an interactive exhibit on __________.",
    "In her new campaign song, Chelsea Clinton raps over the sounds of __________.",
    "In a new tourism campaign, Toronto announces that it has __________.",
    "Batman and Robin agree that __________ marked the beginning of Gotham's decline.",
    "In the new CrowdPublish.TV movie, Hannah struggles with __________ for the first time. ",
    "After George W. Bush became president, Santa started giving bad children __________ instead of coal.",
    "Sadly, kids these days are getting involved with __________.",
    "Life was difficult for cavemen before __________.",
    "I wrote a popular fan fiction book called Harry Potter and the Chamber of __________.",
    "Next on the Sports Channel: The World Cup of __________.",
    "Science will never explain the origin of __________.",
    "My PhD dissertation proves that 5th graders navigate mazes 65% slower after being exposed to __________.",
    "TSA regulations prohibit __________ on flights.",
    "The CIA interrogates US citizens by exposing them to __________.",
    "The Army has been airdropping __________ to the children of Iraq since 2005.",
    "Thanksgiving dinner was totally ruined by __________.",
    "England has declared that __________ is a basic human right.",
    "Life begins with a cry and ends with __________.",
    "Peace! What is it good for?",
    "Love is like __________. You get too much, you get too high.",
    "What is Santa Claus giving up for Lent?",
    "Who is buried in Grant's tomb?",
    "Let us always meet each other with smile, for the smile is the beginning of __________.",
    "The poverty of __________ is the greatest poverty",
    "I have found the paradox, that if you love until it hurts, there can be no more __________.",
    "Love begins at home, and it is not how much we do, but how much love we put in __________.",
    "We feel that what we are doing is just a drop in the ocean. But the ocean is __________ because it's missing that drop.",
    "If we have no peace, it's because we've forgotten __________.",
    "Let us not be satisfied with just giving money; they need your hearts. So spread __________ everywhere you go.",
    "If you can't feed a hundred people, then feed __________.",
    "__________ is a fruit in season at all times, and within reach of every hand.",
    "The hunger for love is much more difficult to remove than the hunger for __________.",
    "If you want a message to be heard, it has to be sent out. To keep a lamp burning, we have to put __________ in it. -Mother Theresa",
    "__________?",
    "What the __________?",
    "Ride the reading __________.",
    "Hope, change, and __________.",
    "It is easier to find men who will volunteer to die, than to find those who are willing to __________.",
    "I came, I saw, I __________.",
    "Experience is the teacher of __________.",
    "It's better to create than to __________.",
    "If you must break the law, do it to seize __________.",
    "Cowards die many times before __________.",
    "I love the name of honor more than I fear __________.",
    "People are quick to believe that which they wish to be __________.",
    "Events of importance are the result of __________.",
    "No one is so brave that they are not disturbed by __________.",
    "I have lived long enough to satisfy __________.",
    "This is the dawning of the age of __________.",
    "I brought __________ back from Mars",
    "What did Michael eat for dessert?",
    "I broke up with my boyfriend because of __________.",
    "__________ only gets better after a few cheeseburgers.",
    "What helps Obama unwind?",
    "__________ is Kermit the Frog's guilty pleasure.",
    "__________ always livens up the funeral.",
    "__________: the car that keeps on driving.",
    "I'm on a fad diet that consists of green beans and __________.",
    "I found __________ in my soup.",
    "What's there a ton of in heaven?",
    "When I am President of the United States, I will create the Department of __________.",
    "When I go to prison, I'll have __________ smuggled in.",
    "When the Brady Bunch was cancelled, Moses called down a Plague of __________.",
    "When I die, I want my ashes scattered on __________.",
    "After Dick Cheney shot his friend in the face, hunters started carrying __________.",
    "Maxwell House is good to the last __________.",
    "Kix: Kid-tested, mother-__________.",
    "Foot-in-__________ disease",
    "__________: There's an app for that.",
    "Four score and seven years ago our mother __________",
    "One small step for women, one giant step for __________",
    "Do unto others as you'd have done to __________.",
    "The Easter Bunny is such a __________.",
    "Don't even think about __________.",
    "I ordered a tuna sandwich, but got __________ instead.",
    "There's nothing to fear but __________.",
    "Do unto others as you'd have done to __________.",
    "This is the dawning of the age of __________.",
    "I applied for a job as a __________.",
    "You can't always get what you want. But sometimes you might get __________.",
    "__________ explains why dinosaurs became extinct.",
    "Where did you discover the Black Plague?",
    "Why did the chicken cross the road?",
    "What caused the Big Bang?",
    "What ever happened to the Rubics Cube?",
    "Where is the Milky Way?",
    "When I grow up, I want to be __________.",
    "In October I will marry __________.",
    "I went to Neptune to see __________.",
    "You know you've arrived when the President names __________ in your honor.",
    "The fifth element on the periodic table is __________.",
    "Newton's second law states that Force equals __________ multiplied by acceleration.",
    "An eye for an eye, a tooth for __________.",
    "What did the priest just say?",
    "I met my husband/wife at __________.",
    "Excuse me while I kiss __________.",
    "I joined a rock band called __________.",
    "The color of my new nail polish is __________.",
    "I made __________ for dinner.",
    "Money for nothing. And __________ for free.",
    "Might as well face it you're addicted to __________.",
    "Wrapped up like a __________ in the middle of the night.",
    "Will Smith: the Fresh Prince of __________.",
    "The meaning of life is to justify __________.",
    "She blinded me with __________.",
    "A bird in the hand is worth __________.",
    "Don't shake your __________ on my bed.",
    "My __________ brings all the boys to the yard.",
    "The first thing I do when I get home is __________.",
    "Who's that girl?",
    "You're a pain in my __________",
    "Mmmmmmm.  I could really go for some __________ right now.",
    "Grandma got run over by a __________.",
    "Would you like __________ with that shake?",
    "Strike while the __________ is hot.",
    "It's always darkest before the __________",
    "Don't bite the hand that __________ you.",
    "If you lie down with dogs, you'll __________.",
    "The pen is mightier than the __________.",
    "Two's company, three's __________.",
    "Better late than __________.",
    "I can't get no __________.",
    "I got __________ in low places.",
    "Where have all the __________ gone?",
    "Mary had a little __________.",
    "Deck the halls with __________",
    "Humpty Dumpty sat on a __________.",
    "Jack and Jill went up the hill to fetch __________.",
    "What are little boys made of?",
    "Yankee Doodle came to town, riding on a __________."
  ];
}

function white() {
  return [
   "Phineas T. Barnum",
   "Little Jive Turkey",
   "Generic trees",
   "Hu Flung Pu",
   "Cactus clouds",
   "Washing the cat",
   "Reading a river",
   "Cantelope brains",
   "Emoticon conference",
   "Zombie ducks",
   "Bacon cupcakes",
   "The place where the dryer hides your socks",
   "Monster ketchup",
   "Rainbow spout",
   "Horseshoe fly",
   "A messy flower",
   "Snoring aquariums",
   "Your little brother",
   "Mouthwash news",
   "A pinstriped hamster",
   "A waste of hair",
   "Peanut butter and sorrow sandwich",
   "Estate hood tax",
   "Popstar sicle",
   "Mustard gas greens",
   "Aerosmith space",
   "Gray poop on",
   "Foxhole trot",
   "Secret Asian man",
   "Lettuce spray",
   "Snow towels",
   "Gamesexchange",
   "Bikes in the fast lane",
   "Triangular coffee",
   "Pants on the Ground",
   "Time thief",
   "Super Nappingman",
   "Ten thousand fire tails",
   "Random word pants",
   "Worldwide Pants",
   "Singing eyeballs",
   "Fear beer",
   "Cod god",
   "Batcat",
   "Fog dog",
   "Sitting on an x-ray",
   "Boring elbows",
   "Toothpaste ants",
   "The snore of a whale",
   "Fire chameleons",
   "Dancing t-shirts",
   "Purple people",
   "Texas toenails",
   "Sassy grass snakes",
   "Pickle popsicles",
   "The lack of a theme",
   "A purring dog",
   "Smiling bulldogs",
   "Tony the Tiger on a bad day",
   "A car driving in the ocean",
   "Formal tennis shoes",
   "Square tires",
   "Beef lollipops",
   "Disco waltzing",
   "Shy Guy comedians",
   "Jumping snakes",
   "Flying trees",
   "Black headlights",
   "Clean bandit",
   "Checkered Hair",
   "Strawberry feet",
   "Washington Native Americans",
   "Snuggling roaches",
   "Church of the Buzzing Bees",
   "Stop sign scented candles",
   "Miss Take's English class",
   "The bus to Mars",
   "Funky cold fire",
   "Burning down the swimming pool",
   "Perfect flaws",
   "Chemically enhanced shoelaces",
   "Staying awake for 5 years",
   "Melting flowers",
   "Bee side",
   "Neon lakes",
   "Red Hot Eggplants",
   "Spaceship from 1820",
   "A plane trip to Mesopotamia",
   "Sequinned songs",
   "Fish on a tricycle",
   "Driving a couch on a freeway",
   "Whirled cheese",
   "Sneaky corpses",
   "Breathing carbon",
   "Blinking mouth",
   "Alice in Wonderbra",
   "The diary of a million year old rock",
   "Hungry like the proboscis",
   "Walk like a Hittite",
   "Theory of relatives",
   "Avocado's number",
   "The pyloric theorem",
   "Speed of fright",
   "Hernia dog",
   "Super muffin",
   "Bronco Bama",
   "Leonardo DiCabriolet",
   "Matt Demon",
   "George Clowny",
   "Jake Gynocologichaal",
   "John Revolta",
   "Sean Penncil",
   "Humphrey Bogus",
   "Greta Garbled",
   "Sickgurney Weaver",
   "Susan Saranwrap",
   "George Snuffleupagus",
   "Brad Peach Pitt",
   "Normal Al Yankovic", 
   "Supah Anvil of Doom",
   "Carnival of Coal",
   "Stinky Death Breath",
   "Defeated Santa Sanity",
   "Indiana Jones and the Infernal Machine",
   "My grain headache",
   "Molotov Solution",
   "Death at a funeral",
   "Swallowing the Sun",
   "Awkward Turtle",
   "Serious George",
   "Tickled too much Elmo",
   "Jello pudding pops",
   "Bro-down showdown",
   "Cardboard armor battle royale",
   "Thug life cat",
   "Gaming on a toaster",
   "GPS saying 'head west' like its Oregon Trail",
   "Eating a whole bag of Warheads at once",
   "Hating Justin Bieber before it was cool",
   "Chicken hat",
   "Star Shrek Enterprise",
   "Makin' dat Youtube monies",
   "Getting jacked without the gym",
   "Getting a picture of a thumbs down in a fortune cookie",
   "Techno Viking",
   "Neckbeard the pirate",
   "Avatar the Last Hairbender",
   "Pooptarts",
   "Mean muggin'",
   "Forever Alone Guy",
   "Eager Face Engaged",
   "Taco Monster",
   "Broseidon, Lord of the broceans",
   "Turban Outfitters",
   "Giant Snail Jousting",
   "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTP4gP-a5OGo1jmMWswiHduLNoAz8pv_wwtNv12OZiUP0HuF1iLqCUdKCc",
   "http://budgetjustified.com/images/bowlcherries.jpg",
   "http://budgetjustified.com/images/lisaSZshirtHeadless.png",
   "http://budgetjustified.com/images/bearlaugh.jpg",
   "http://budgetjustified.com/images/phd.png",
   "http://budgetjustified.com/images/cpLogo100.png",
   "http://budgetjustified.com/images/babyMichaelEngineer.jpg",
   "http://budgetjustified.com/images/llama.JPG",
   "https://upload.wikimedia.org/wikipedia/commons/2/27/Banana_slug_at_UCSC.jpg",
   "http://budgetjustified.com/images/bowlcherries.jpg",
   "http://budgetjustified.com/images/lisaSZshirtHeadless.png",
   "http://budgetjustified.com/images/bearlaugh.jpg",
   "http://budgetjustified.com/images/phd.png",
   "http://budgetjustified.com/images/cpLogo100.png",
   "http://budgetjustified.com/images/babyMichaelEngineer.jpg",
   "http://budgetjustified.com/images/llama.JPG",
   "https://upload.wikimedia.org/wikipedia/commons/2/27/Banana_slug_at_UCSC.jpg",
   "http://images.sodahead.com/polls/002175773/61979835_oxymoron_xlarge.jpeg",
   "https://upload.wikimedia.org/wikipedia/commons/a/a1/Stone_writing.jpg",
   "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Stop_Defacing_Signs.jpg/170px-Stop_Defacing_Signs.jpg",
   "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/Irony.jpg/576px-Irony.jpg",
   "http://budgetjustified.com/images/bankruptcy.jpg",
   "http://budgetjustified.com/images/cancer.jpg",
   "http://budgetjustified.com/images/ciaIntelligence.jpg",
   "http://budgetjustified.com/images/cleanDirt.jpg",
   "http://budgetjustified.com/images/obesity.jpg",
   "http://budgetjustified.com/images/realityTV.jpg",
   "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTP4gP-a5OGo1jmMWswiHduLNoAz8pv_wwtNv12OZiUP0HuF1iLqCUdKCc",
   "http://img.wikinut.com/img/3p9jy3977y0n_32j/jpeg/724x5000/Leonardo-da-Vinci-Public-domain-Wikimedia-Common.jpeg",
   "http://www.bittbox.com/wp-content/uploads/2009/02/public_domain_astronomy_30.jpg"
  ];
}

exports.getDeck = getDeck;
